all:

  knp_markdown:

    jquery_use:     false
    jquery_src:     /knpMarkdownPlugin/jquery-1.4.2.min.js

    markitup_dir:   /knpMarkdownPlugin/markitup
    markitup_set:   markdown
    markitup_skin:  simple

    preview:        true
    preview_route:  knp_markdown_preview